### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by tanguien** [tanguien/tanguien#5]
I am experiencing an error in my Angular project when trying to render a list of items. Below are the details:

Angular Version: 13.0.0
npm Version: 8.1.0
Operating System: Windows 10
Steps to Reproduce:

Clone the repository: git clone https://github.com/username/repo.git
Navigate to the project directory: cd repo
Install dependencies: npm install
Run the application: ng serve
Visit http://localhost:4200/items in the browser.
Expected Behavior:
The items should be displayed in a list format without errors.

Actual Behavior:
I receive the following error in the console:

ERROR TypeError: Cannot read properties of undefined (reading 'map') 

Additional Context:
I've checked the service that fetches the data, and the API returns the expected JSON response. I suspect it might be a timing issue with the asynchronous call to the service.

**Comment by webmaster1225** [comment]
Hello, @tanguien

I think there are some problems in your project. The issues can be caused by:

1. Make sure that the service that fetches the data is actually returning an array. You can log the response to see if it's what you expect.
2. Initialize the variable that will hold your list of items to ensure it starts as an empty array. This prevents attempting to call map on undefined.
3. Ensure that there are no network issues preventing the API from responding, such as CORS problems or issues with the API server. You can verify this in the Network tab of your browser's developer tools.

These can't still solve your issues, please let me know.
I'd like to see the part for issue correctly.
Thanks

**Comment by tanguien** [comment]
Hello, @webmaster1225
Thanks for your help.
I tried with your solution methods and solved with the second one.
Thanks
